export const INITIAL_DATA = {
	isSignin: false,
	pass: 'passguard',
	data: [
		{
			id: 1,
			name: 'Google',
			url: 'https://www.google.com',
			username: 'google@gmail.com',
			password: 'google',
			createdAt: new Date(),
			lastModified: new Date(),
			lastUsed: null,
		},
		{
			id: 2,
			name: 'Facebook',
			url: 'https://www.facebook.com',
			username: 'facebook@gmail.com',
			password: 'facebook',
			createdAt: new Date(),
			lastModified: new Date(),
			lastUsed: null,
		},
		{
			id: 3,
			name: 'Twitter',
			url: 'https://www.twitter.com',
			username: 'twitter@gmail.com',
			password: 'twitter',
			createdAt: new Date(),
			lastModified: new Date(),
			lastUsed: null,
		},
		{
			id: 4,
			name: 'Instagram',
			url: 'https://www.instagram.com',
			username: 'instagram@gmail.com',
			password: 'instagram',
			createdAt: new Date(),
			lastModified: new Date(),
			lastUsed: null,
		},
		{
			id: 5,
			name: 'LinkedIn',
			url: 'https://www.linkedin.com',
			username: 'linkedin@gmail.com',
			password: 'linkedin',
			createdAt: new Date(),
			lastModified: new Date(),
			lastUsed: null,
		},
	],
};
